#!/usr/bin/env python

import sys
import os

def main(args):
    """
    Syntax is `bkm nickname [directory]`. Directory defaults to PWD
    """
    if len(args) < 1:
        raise ValueError("Not enough args. Usage: `bkm nickname [directory]`")
    
    nickname = args[0]
    cwd = os.getcwd()
    with open(os.path.expanduser('~/.bkm'), 'a') as fh:
        fh.write('alias {}="cd {}"\n'.format(nickname, cwd))


if __name__ == '__main__':
    main(sys.argv[1:])

